pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Use GitHub credentials to clone repository
                withCredentials([usernamePassword(credentialsId: 'd39691d9-f12c-4abd-89ec-8639e722b3f7', usernameVariable: 'GITHUB_USERNAME', passwordVariable: 'GITHUB_PASSWORD')]) {
                    git credentialsId: 'github-credentials', url: 'https://github.com/roshnihande/capstone-project.git'
                }
            }
        }

        
        stage('Build Docker Image') {
            steps {
              script {
                  // Build Docker image
                def dockerImage = docker.build('my-django-app:latest', './django_project')
            }
            }
        }
        
        stage('Run Tests') {
            steps {
                // Run automated tests to validate the application's functionality
                // Modify this step according to your Django application's testing framework
                sh 'python manage.py test'
            }
        }
        
        stage('Deploy to Minikube') {
            steps {
                // Deploy the Django application to the Minikube Kubernetes cluster
                // Modify this step according to your deployment process (e.g., kubectl apply)
                sh 'kubectl apply -f deployment.yaml'
            }
        }
    }
}
